In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
arr=np.array(42)
print(arr)

42


In [4]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [5]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [6]:
arr=np.zeros((5,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [8]:
arr=np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [9]:
arr=np.empty((3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [13]:
arr=np.array([1,2,3])
print("before converting: ",arr,arr.dtype)
new=arr.astype('f')
print("after converting: ",new,new.dtype)

before converting:  [1 2 3] int64
after converting:  [1. 2. 3.] float32


In [14]:
arr1=np.arange(10)
arr2=np.random.randn(10)
print("array 1\n",arr1,arr1.dtype)
print("array 2\n",arr2,arr2.dtype)
new=arr1.astype(arr2.dtype)
print("new array",new,new.dtype)

array 1
 [0 1 2 3 4 5 6 7 8 9] int64
array 2
 [-0.92185037 -1.7666254  -1.95593733  0.05904316 -1.39712818  0.6151593
  0.69582629  0.50849502 -0.87741086 -0.13594112] float64
new array [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [15]:
strr=np.array(['hello','world','numpy'])
print(strr)

['hello' 'world' 'numpy']


In [16]:
a=np.array([1.,2.,3.,4.])
b=np.array([5.,6.,7.,8.])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [18]:
arr=np.arange(12)
new=arr.reshape(4,3)
print(new)
new=arr.reshape((4,3),order='f')
print("\n",new)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [20]:
arr=np.array([[1,2,3,4,9,10],[5,6,7,8,11,12]])
print(arr)
new=arr.reshape(3,2,2)
print("\n",new)
new1=new.reshape(3,-1)
print("\n reshape(3,-1) \n",new1)


[[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]

 [[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]

 reshape(3,-1) 
 [[ 1  2  3  4]
 [ 9 10  5  6]
 [ 7  8 11 12]]


In [22]:
arr=np.array([[10,20],[30,40]])
print("original:\n",arr)
flat=arr.flatten()
flat[0]=990
print("flattened:\n", flat)
print("original:\n",arr)
rav=arr.ravel()
rav[1]=888
print("raveled:\n",rav)
print("original:\n",arr)

original:
 [[10 20]
 [30 40]]
flattened:
 [990  20  30  40]
original:
 [[10 20]
 [30 40]]
raveled:
 [ 10 888  30  40]
original:
 [[ 10 888]
 [ 30  40]]


In [24]:
arr=np.array([[1,2],[3,4]])
arr2=np.array([[2,1],[3,5]])
gre=arr>arr2
less=arr<arr2
equal=arr==arr2
print(gre)
print(less)
print(equal)

[[False  True]
 [False False]]
[[ True False]
 [False  True]]
[[False False]
 [ True False]]


In [25]:
x=np.arange(10)
print("x= ",x)
print("\n x[:5]= ",x[:5])
print("\n x[5:]= ",x[5:])
print("\n x[::2]= ",x[::2])
print("\n x[5::-2]= ",x[5::-2])


x=  [0 1 2 3 4 5 6 7 8 9]

 x[:5]=  [0 1 2 3 4]

 x[5:]=  [5 6 7 8 9]

 x[::2]=  [0 2 4 6 8]

 x[5::-2]=  [5 3 1]


In [26]:
x=np.arange(10)
print(x)
x[5:]=2
print("\n after broadcasting1",x)

x[::2]=100
print("\n after broadcasting2",x)

[0 1 2 3 4 5 6 7 8 9]

 after broadcasting1 [0 1 2 3 4 2 2 2 2 2]

 after broadcasting2 [100   1 100   3 100   2 100   2 100   2]


In [27]:
x=np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
print(x[0])
print(x[2,0])
print(x[1][2])
print(x[2,-1])
print(x[0])

[12  5  2  4]
1
8
7
[12  5  2  4]


In [28]:
a=np.arange(12).reshape(3,4)
print("a= \n",a)
b=a>4
print("b= \n",b)
print("a[b]= \n",a[b])
a[b]=1
print("a= \n",a)

a= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b= 
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
a[b]= 
 [ 5  6  7  8  9 10 11]
a= 
 [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [29]:
arr=np.arange(12).reshape((3,4))
print(arr)
print("transpone .T")
print(arr.T)
print(np.transpose(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transpone .T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [30]:
arr=np.arange(12).reshape((3,4))
print(np.dot(arr, arr.T))

[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [31]:
arr=np.arange(12).reshape((3,4))
print(arr)
print("swap 0 and 1:")
print(np.swapaxes(arr,0,1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
swap 0 and 1:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [34]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.multiply(arr1,arr2)
print(result)
result=np.matmul(arr1,arr2)
print(result)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
